# Game Settings Configuration for Forgotten Depths MUD

# Player Settings
player:
  starting_stats:
    strength: 10
    dexterity: 10
    constitution: 10
    intelligence: 10
    wisdom: 10
    charisma: 10

  starting_resources:
    health: 100
    mana: 50
    gold: 100

  # Leveling Settings
  leveling:
    base_xp_per_level: 100           # Base XP needed for level 2
    xp_multiplier: 1.5               # Each level requires XP = base * (multiplier ^ (level - 1))
    stat_points_per_level: 2         # Stat points awarded per level
    hp_per_level: 10                 # Base HP increase per level
    mana_per_level: 5                # Base mana increase per level
    max_level: 50                    # Maximum level cap

  # Hunger and Thirst Settings
  hunger_thirst:
    hunger_decay_per_tick: 0.005      # Decay rate per tick (0.05 = 3/min = ~33 mins to starve)
    thirst_decay_per_tick: 0.005     # Decay rate per tick (0.075 = 4.5/min = ~22 mins to dehydrate)
    low_warning_threshold: 20        # Warn when hunger/thirst drops below this
    starvation_damage_per_tick: 0.05 # HP damage per tick when starving
    dehydration_damage_per_tick: 0.1 # HP damage per tick when dehydrated

  inventory:
    default_size: 20
    max_size: 100
    starting_items:
      - "bread"
      - "health_potion_small"

# World Settings
world:
  respawn_time: 300
  room_capacity: 50
  weather_enabled: false
  day_night_cycle: false
  map_shows_only_explored: true  # Only show rooms player has visited in map command

# Dungeon Settings
# Define wandering mob configs for each dungeon area
wandering_mobs:
  arena_dungeon:
    enabled: true
    max_wandering_mobs: 5        # Maximum number of wandering mobs in this dungeon
    spawn_interval: 30            # Spawn check interval in seconds
    spawn_chance: 0.3             # 30% chance to spawn per check
    movement_chance: 0.2          # 20% chance to move per tick
    mob_pool:                     # Mobs that can spawn as wanderers
      - id: "rat"
        weight: 40
      - id: "goblin_scout"
        weight: 35
      - id: "skeleton_warrior"
        weight: 25

  dungeon1:
    enabled: true
    max_wandering_mobs: 10       # Maximum number of wandering mobs in this dungeon
    spawn_interval: 30            # Spawn check interval in seconds
    spawn_chance: 0.5             # 50% chance to spawn per check
    movement_chance: 0.3          # 30% chance to move per tick
    mob_pool:                     # Mobs that can spawn as wanderers
      - id: "rat"
        weight: 40
      - id: "goblin_scout"
        weight: 35
      - id: "skeleton_warrior"
        weight: 25

  dungeon2:
    enabled: true
    max_wandering_mobs: 12       # Maximum number of wandering mobs in this dungeon
    spawn_interval: 25            # Spawn check interval in seconds
    spawn_chance: 0.6             # 60% chance to spawn per check
    movement_chance: 0.4          # 40% chance to move per tick (more active)
    mob_pool:                     # Mobs that can spawn as wanderers (tougher mobs)
      - id: "goblin_scout"
        weight: 30
      - id: "skeleton_warrior"
        weight: 40
      - id: "rat"
        weight: 30

  dungeon3:
    enabled: true
    max_wandering_mobs: 15       # Maximum number of wandering mobs in this dungeon
    spawn_interval: 20            # Spawn check interval in seconds
    spawn_chance: 0.7             # 70% chance to spawn per check (very dangerous)
    movement_chance: 0.5          # 50% chance to move per tick (highly active)
    mob_pool:                     # Mobs that can spawn as wanderers (toughest mobs)
      - id: "skeleton_warrior"
        weight: 50
      - id: "goblin_scout"
        weight: 30
      - id: "rat"
        weight: 20

# Combat Settings
combat:
  turn_based: false
  auto_attack: true
  damage_variance: 0.2
  armor_effectiveness: 0.1

# Economy Settings
economy:
  vendor_buy_rate: 0.5
  vendor_sell_rate: 1.2
  tax_rate: 0.05
  inflation_rate: 0.0

# Communication Settings
communication:
  max_message_length: 500
  profanity_filter: false
  chat_channels:
    - "global"
    - "newbie"
    - "trade"

  message_history: 100

# Quest Settings
quests:
  auto_accept: false
  completion_rewards_multiplier: 1.0
  daily_quests: false

# Magic Settings
magic:
  mana_regeneration: 1
  spell_failure_chance: 0.05
  reagent_required: false

# Death Settings
death:
  permadeath: false
  corpse_decay_time: 600
  death_penalty:
    experience_loss: 0.1
    item_loss: false
    stat_loss: false

# Admin Settings
admin:
  godmode_available: true
  building_enabled: true
  player_editing: true